import pandas as pd
import numpy as np


data = pd.read_csv('ICESING.csv', delimiter='\t')

print(data.head())
data['word_S'] = np.where(data['n_sent'] != 0, data['n_word'] / data['n_sent'], 0)
data['lexical_density'] = np.where(data['n_word'] != 0, data['ld'] / data['n_word'], 0)
data['nn_W'] = np.where(data['n_word'] != 0, data['nn'] / data['n_word'], 0)
data['np_W'] = np.where(data['n_word'] != 0, data['np'] / data['n_word'], 0)
data['nominal_W'] = np.where(data['n_word'] != 0, data['nom'] / data['n_word'], 0)
data['neoclass_W'] = np.where(data['n_word'] != 0, data['neo'] / data['n_word'], 0)
data['poss_pronoun_W'] = np.where(data['n_word'] != 0, data['poss'] / data['n_word'], 0)
data['pronoun_all_W'] = np.where(data['n_word'] != 0, data['pronoun'] / data['n_word'], 0)
data['p1_perspron_P'] = np.where(data['pronoun'] != 0, data['p1'] / data['pronoun'], 0)
data['p2_perspron_P'] = np.where(data['pronoun'] != 0, data['p2'] / data['pronoun'], 0)
data['p3_perspron_P'] = np.where(data['pronoun'] != 0, data['p3'] / data['pronoun'], 0)
data['it_P'] = np.where(data['pronoun'] != 0, data['pit'] / data['pronoun'], 0)
data['pospers1_W'] = np.where(data['n_word'] != 0, data['pospers1'] / data['n_word'], 0)
data['pospers2_W'] = np.where(data['n_word'] != 0, data['pospers2'] / data['n_word'], 0)
data['pospers3_W'] = np.where(data['n_word'] != 0, data['pospers3'] / data['n_word'], 0)
data['adj_W'] = np.where(data['n_word'] != 0, data['adj'] / data['n_word'], 0)
data['atadj_W'] = np.where(data['n_word'] != 0, data['atadj'] / data['n_word'], 0)
data['predadj_W'] = np.where(data['n_word'] != 0, (data['adj'] - data['atadj']) / data['n_word'], 0)
data['prep_W'] = np.where(data['n_word'] != 0, data['prep'] / data['n_word'], 0)
data['finite_S'] = np.where(data['n_sent'] != 0, data['fin'] / data['n_sent'], 0)
data['past_tense_F'] = np.where(data['fin'] != 0, data['past'] / data['fin'], 0)
data['will_F'] = np.where(data['fin'] != 0, data['will'] / data['fin'], 0)
data['modal_verb_V'] = np.where(data['v'] != 0, data['vm'] / data['v'], 0)
data['verb_W'] = np.where(data['n_word'] != 0, data['v'] / data['n_word'], 0)
data['infinitive_F'] = np.where(data['fin'] != 0, data['inf'] / data['fin'], 0)
data['passive_F'] = np.where(data['fin'] != 0, data['pass'] / data['fin'], 0)
data['coordination_F'] = np.where(data['fin'] != 0, data['coord'] / data['fin'], 0)
data['subordination_F'] = np.where(data['fin'] != 0, data['subord'] / data['fin'], 0)
data['interrogative_S'] = np.where(data['n_sent'] != 0, data['interr'] / data['n_sent'], 0)
data['imperative_S'] = np.where(data['n_sent'] != 0, data['imper'] / data['n_sent'], 0)
data['title_W'] = np.where(data['n_word'] != 0, data['title'] / data['n_word'], 0)
data['salutation_S'] = np.where(data['n_sent'] != 0, data['salutgreet'] / data['n_sent'], 0)
data['place_adv_W'] = np.where(data['n_word'] != 0, data['rl'] / data['n_word'], 0)
data['time_adv_W'] = np.where(data['n_word'] != 0, data['rt'] / data['n_word'], 0)
data['nom_initial_S'] = np.where(data['n_sent'] != 0, data['nptheme'] / data['n_sent'], 0)
data['prep_initial_S'] = np.where(data['n_sent'] != 0, data['pptheme'] / data['n_sent'], 0)
data['adv_initial_S'] = np.where(data['n_sent'] != 0, data['advtheme'] / data['n_sent'], 0)
data['text_initial_S'] = np.where(data['n_sent'] != 0, data['cctheme'] / data['n_sent'], 0)
data['wh_initial_S'] = np.where(data['n_sent'] != 0, data['whtheme'] / data['n_sent'], 0)
data['disc_initial_S'] = np.where(data['n_sent'] != 0, data['disctheme'] / data['n_sent'], 0)
data['nonfin_initial_S'] = np.where(data['n_sent'] != 0, data['totheme'] / data['n_sent'], 0)
data['subord_initial_S'] = np.where(data['n_sent'] != 0, data['subordtheme'] / data['n_sent'], 0)

data['verb_initial_S'] = np.where(data['n_sent'] != 0, data['verbtheme'] / data['n_sent'], 0)
data.to_csv('updated_file.csv', index=False)
